version: '3.8'

services:
  healthcare-bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-production-secret-key-change-this}
      - HOST=0.0.0.0
      - PORT=5002
      - DEBUG=false
      - LOG_LEVEL=INFO
      - LOG_FILE=/app/logs/healthcare-bot.log
      - STRUCTURED_LOGGING=true
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5002/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  logs:
  data: 